AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Models/AutoComponentsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoComponentsStore.Domain.Entities;

namespace AutoComponentsStore.WebUI.Models
{
    public class AutoComponentsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoComponentsStore.Domain.Entities;

namespace AutoComponentsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoComponentsStore.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Controllers/AutoComponentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoComponentsStore.Domain.Abstract;
using AutoComponentsStore.WebUI.Models;

namespace AutoComponentsStore.WebUI.Controllers
{
    public class AutoComponentsController : Controller
    {
        private IAutoComponentsRepository repository;
        public int pageSize = 4;

        // GET: AutoComponents
        public AutoComponentsController(IAutoComponentsRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            //return View(repository.Products
            //    .OrderBy(game => game.ProductId)
            //    .Skip((page - 1) * pageSize)
            //    .Take(pageSize));

            AutoComponentsListViewModel model = new AutoComponentsListViewModel
            {
                Products = repository.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.ProductId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Count(prod => prod.Category == category)
            },
                CurrentCategory = category
            };
            return View(model);

        }
    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoComponentsStore.Domain.Abstract;
using AutoComponentsStore.Domain.Entities;
using AutoComponentsStore.WebUI.Models;

namespace AutoComponentsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IAutoComponentsRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IAutoComponentsRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }


        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product game = repository.Products
                .FirstOrDefault(g => g.ProductId == productId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product game = repository.Products
                .FirstOrDefault(g => g.ProductId == productId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoComponentsStore.Domain.Abstract;

namespace AutoComponentsStore.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private IAutoComponentsRepository repository;

        public NavigationController(IAutoComponentsRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/AutoComponents/List.cshtml
@using AutoComponentsStore.Domain.Entities
@model AutoComponentsStore.WebUI.Models.AutoComponentsListViewModel

@{
    ViewBag.Title = "Товары";
}

@foreach (var p in @Model.Products)
{
    @Html.Partial("AutoComponentsSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Cart/Checkout.cshtml
@model AutoComponentsStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "AutoComponentStore: форма заказа";
}

<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введи ваши контактные данные, и мы сразу отправим товар!</p>


@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Cart/Index.cshtml
@model AutoComponentsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "AutoComponentsStore: ваша корзина";
}

<!-- ... -->
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Ваша корзина</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Кол-во</th>
            <th>Игра</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("# руб")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("# руб"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("GameId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary" })
</div>

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Cart/Summary.cshtml
@model AutoComponentsStore.Domain.Entities.Cart

@{
    ViewBag.Title = "Название и цена";   
}

<a href=@Url.Action("Index", "Cart", new {returnUrl = Request.Url.PathAndQuery})>
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) игр,
    @Model.ComputeTotalValue().ToString("# руб")
</a>

@*<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery })
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>*@

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Navigation/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой", "List", "AutoComponents", null,
    new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "AutoComponents",
    action = "List",
    category = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
            + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
})
}

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Shared/AutoComponentsSummary.cshtml
@model AutoComponentsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

AutoComponents/AutoComponentsStore/AutoComponentsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="~/Content/template/css/style.default.css" rel="stylesheet" id="theme-stylesheet">


    <!-- Css animations  -->
    @*<link href="~/Content/template/css/animate.css" rel="stylesheet">*@

    
    <title>@ViewBag.Title</title>
    @*<style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>*@
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
</head>
<body>
<div id="All">
    <header>
        <div id="top">

            <!-- *** TOP ***
        _________________________________________________________ -->
            <div class="container">
                <div class="row">
                    <div class="col-xs-5 contact">
                        <p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
                        <p class="hidden-md hidden-lg">
                            <a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a> <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                        </p>
                    </div>
                    <div class="col-xs-7">
                        <div class="social">
                            <a href="#" class="external facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
                            <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                        </div>

                        <div class="login">
                            <a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-sign-in"></i> <span class="hidden-xs text-uppercase">Sign in</span></a>
                            <a href="customer-register.html"><i class="fa fa-user"></i> <span class="hidden-xs text-uppercase">Sign up</span></a>
                        </div>
                    </div>
                </div>
             </div>
        </div>
            <!-- *** TOP END *** -->
            <!-- *** NAVBAR ***
            _________________________________________________________ -->
            <div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">
                <div class="navbar navbar-default yamm" role="navigation" id="navbar">
                    <div class="container">
                        <div class="navbar-header">
                            <a class="navbar-brand home" href="index.html">
                                <img src="~/Content/template/img/logo.png" alt="Universal logo" class="hidden-xs hidden-sm">
                                <img src="~/Content/template/img/logo-small.png" alt="Universal logo" class="visible-xs visible-sm"><span class="sr-only">AutoComponentsStore - магазин автозапчастей</span>
                            </a>
                            <div class="navbar-buttons">
                                <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
                                    <span class="sr-only">Toggle navigation</span>
                                    <i class="fa fa-align-justify"></i>
                                </button>
                            </div>
                        </div>
                        <div class="navbar-collapse collapse" id="navigation">
                            <ul class="nav navbar-nav navbar-right">

                                <li class="dropdown use-yamm yamm-fw">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        Главная<b></b></a>
                                </li>
                                <li class="dropdown use-yamm yamm-fw">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Каталог<b></b></a>
                                </li>
                                <li class="dropdown use-yamm yamm-fw">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">О Компании<b></b></a>
                                </li>
                                <li class="dropdown use-yamm yamm-fw">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Контакты<b></b></a>
                                </li>
                                <li class="dropdown use-yamm yamm-fw">
                                        @Html.Action("Summary", "Cart")
                                </li>
                            </ul>
                        </div>  
                    </div>
                 </div>
               </div>
    </header>

    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>AutoComponentsStore - магазин автозапчастей</h1>
                </div>
                <div class="col-md-5">
                    <ul class="breadcrumb">
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li>Category with left sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="row panel">
            <div id="categories" class="col-xs-3">
                @Html.Action("Menu", "Navigation")
            </div>
        </div>
        @RenderBody()

    </div>

    <div class="container body-content">
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My Diploma ASP.NET Application</p>
        </footer>
    </div>
</div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')
    </script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>